<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Chair.obj" />
    <None Remove="Assets\Door.obj" />
    <None Remove="Assets\House.obj" />
    <None Remove="Assets\Key.obj" />
    <None Remove="Assets\Lantern.obj" />
    <None Remove="Assets\Spoon.obj" />
    <None Remove="Assets\Table.obj" />
    <None Remove="Assets\Textures\chair.png" />
    <None Remove="Assets\Textures\door.jpg" />
    <None Remove="Assets\Textures\door.png" />
    <None Remove="Assets\Textures\grass.png" />
    <None Remove="Assets\Textures\house.jpg" />
    <None Remove="Assets\Textures\house.png" />
    <None Remove="Assets\Textures\key.jpg" />
    <None Remove="Assets\Textures\key.png" />
    <None Remove="Assets\Textures\lantern.jpg" />
    <None Remove="Assets\Textures\lantern.png" />
    <None Remove="Assets\Textures\spoon.png" />
    <None Remove="Assets\Textures\table.jpg" />
    <None Remove="Assets\Textures\table.png" />
    <None Remove="Shaders\fragment.glsl" />
    <None Remove="Shaders\vertex.glsl" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Chair.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Door.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\House.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Key.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Lantern.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Spoon.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Table.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\chair.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\door.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\grass.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\house.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\key.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\lantern.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\spoon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\table.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Shaders\fragment.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Shaders\vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
  </ItemGroup>

</Project>
